# Generated by Django 2.0.6 on 2018-06-22 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='enlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('contenido', models.TextField()),
                ('puntuacion', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=2)),
                ('visto', models.IntegerField(default=0)),
                ('categoria', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='Wikipy.Categoria')),
                ('relacionadas', models.ManyToManyField(blank=True, to='Wikipy.Pagina')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Wikipy.Categoria')),
            ],
        ),
        migrations.AddField(
            model_name='pagina',
            name='subcategoria',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='Wikipy.Subcategoria'),
        ),
        migrations.AddField(
            model_name='enlace',
            name='pagina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Wikipy.Pagina'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Wikipy.Grupo'),
        ),
    ]
