# Generated by Django 2.0.6 on 2018-06-22 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Wikipy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagina',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Wikipy.Categoria'),
        ),
        migrations.AlterField(
            model_name='pagina',
            name='subcategoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Wikipy.Subcategoria'),
        ),
    ]
