# Generated by Django 2.0.6 on 2018-06-22 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Wikipy', '0002_auto_20180622_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagina',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Wikipy.Categoria'),
        ),
        migrations.AlterField(
            model_name='pagina',
            name='subcategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Wikipy.Subcategoria'),
        ),
    ]
