# Generated by Django 2.0.6 on 2018-06-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wikipy', '0004_auto_20180622_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editor', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='enlace',
            name='pagina',
        ),
        migrations.DeleteModel(
            name='enlace',
        ),
    ]
