# Generated by Django 2.0.5 on 2018-05-27 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('descripcion', models.TextField()),
                ('codigo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Docu.Categoria')),
            ],
        ),
        migrations.AddField(
            model_name='pagina',
            name='Subcategodia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Docu.Subcategoria'),
        ),
        migrations.AddField(
            model_name='pagina',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Docu.Categoria'),
        ),
        migrations.AddField(
            model_name='pagina',
            name='subpagina',
            field=models.ManyToManyField(to='Docu.Pagina'),
        ),
    ]
