# Generated by Django 2.0.5 on 2018-05-27 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Docu', '0002_auto_20180527_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagina',
            old_name='Subcategodia',
            new_name='Subcategoria',
        ),
    ]
