# Generated by Django 2.0.5 on 2018-05-28 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Docu', '0003_auto_20180527_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='nombre',
            new_name='nombre_cat',
        ),
        migrations.RenameField(
            model_name='subcategoria',
            old_name='nombre',
            new_name='nombre_sub',
        ),
    ]
