# Generated by Django 2.0.5 on 2018-05-28 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Docu', '0004_auto_20180528_0014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagina',
            old_name='Subcategoria',
            new_name='subcategoria',
        ),
    ]
