# Generated by Django 2.0.5 on 2018-05-29 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Docu', '0005_auto_20180528_0016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enlaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enlace', models.CharField(max_length=100)),
                ('pagina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Docu.Pagina')),
            ],
        ),
    ]
