# Generated by Django 2.0.5 on 2018-05-30 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docu', '0006_enlaces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagina',
            name='codigo',
            field=models.TextField(blank=True),
        ),
    ]
